### ISSUE TITLE
Two things

### ISSUE THREAD

**Issue by inorganik** [michaeltyson/TPAACAudioConverter#7]
Hi, thanks for this awesome class! I have a couple questions- 

1. Is it possible to convert to mp3? From what I can tell from Apple's documentation it seems like you can't (See Table 1.2 in [this reference](https://developer.apple.com/library/ios/documentation/AudioVideo/Conceptual/MultimediaPG/UsingAudio/UsingAudio.html)) but I wonder if you've tried it.
2. Could you convert this project to ARC? I converted the class, and there are two places where Xcode wants to fix a cast but does so incorrectly, leaving out a closing parenthesis. Most people will want ARC version of the class, so that would be helpful.

Thanks again.

**Comment by heliumdice** [comment]
I would love an ARC version of this class 

@inorganik did you manage to convert this to work with ARC?

Thanks

**Comment by inorganik** [comment]
Hey @heliumdice I committed my ARC conversion here: https://github.com/inorganik/TPAACAudioConverter 

It works great however I commented out a good deal of code so the error handling is probably not as good now. I use it in a project to convert lpcm recordings to mp4 and have never had any errors.
